version: '3.8'

services:
  extraction_api:
    build:
      context: ./extraction
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./extraction:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # .env dosyasını backend servisine ekle

  prediction_api:
    build:
      context: ./prediction
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./prediction:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # .env dosyasını backend2 servisine ekle

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: bash -c "npm install && npm run serve"
    env_file:
      - .env  # .env dosyasını frontend servisine ekle (eğer gerekiyorsa)
